# Generated by Django 4.0.2 on 2022-03-12 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('core', '0005_alter_customuser_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_order', '0005_alter_salesorder_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number_key', models.PositiveIntegerField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('net_price', models.IntegerField(default=0)),
                ('gross_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Folyamatban'), ('completed', 'Teljesítve'), ('cancelled', 'Sztornózva')], max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'Készpénz'), ('card', 'Utalás')], max_length=50)),
                ('billing_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('conn_sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_order.salesorder')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('original_producer', models.CharField(max_length=100)),
                ('original_net_price', models.IntegerField(default=0)),
                ('original_vat', models.IntegerField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('package_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagetype')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
