# Generated by Django 4.0.2 on 2022-04-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='conn_sales_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_order.salesorder'),
        ),
    ]
