# Generated by Django 4.0.2 on 2022-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
