# Generated by Django 4.0.2 on 2022-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='debt',
            field=models.IntegerField(default=0),
        ),
    ]
