# Generated by Django 4.0.2 on 2022-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billing_address_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_house_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_street_name',
            field=models.CharField(default='valami', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_zip_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
