# Generated by Django 4.0.2 on 2022-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_invoice_billing_address_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_mode',
            field=models.CharField(choices=[('personal', 'Személyes átvétel'), ('delivery', 'Szállítás')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
