# Generated by Django 4.0.2 on 2022-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_delivery_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Folyamatban'), ('completed', 'Kiegyenlítve'), ('cancelled', 'Sztornózva')], max_length=50),
        ),
    ]
