# Generated by Django 4.0.2 on 2022-04-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoiceitem_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
