# Generated by Django 4.0.2 on 2022-04-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Készpénz'), ('card', 'Utalás')], max_length=50)),
                ('delivery_mode', models.CharField(choices=[('personal', 'Személyes átvétel'), ('delivery', 'Szállítás')], max_length=50)),
                ('net_price', models.IntegerField(default=0)),
                ('gross_price', models.IntegerField(default=0)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('original_customer_name', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
