# Generated by Django 4.0.2 on 2022-04-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_action_percent'),
        ('admin_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('original_producer', models.CharField(max_length=100)),
                ('original_net_price', models.IntegerField(default=0)),
                ('original_vat', models.IntegerField()),
                ('original_package_quantity', models.PositiveIntegerField()),
                ('original_package_display', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('package_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagetype')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
