# Generated by Django 4.0.2 on 2022-04-25 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_action_percent_alter_product_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='percent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
