# Generated by Django 4.0.2 on 2022-04-28 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_action_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='percent',
            field=models.PositiveIntegerField(error_messages={'max_value': 'Az érték legyen kisebb van egyenlő, mint 100.'}, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
