# Generated by Django 4.0.2 on 2022-04-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_core', '0001_initial'),
        ('product', '0008_alter_action_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('salesbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_core.salesbase')),
                ('document_number_key', models.PositiveIntegerField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Folyamatban'), ('completed', 'Teljesítve'), ('cancelled', 'Lemondva')], max_length=50)),
            ],
            bases=('admin_core.salesbase',),
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('original_producer', models.CharField(max_length=100)),
                ('original_net_price', models.IntegerField(default=0)),
                ('original_vat', models.IntegerField()),
                ('original_package_quantity', models.PositiveIntegerField()),
                ('original_package_display', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('delivery_note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_note.deliverynote')),
                ('package_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagetype')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
