# Generated by Django 4.0.2 on 2022-03-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_order', '0007_rename_shipping_city_salesorder_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number_key', models.PositiveIntegerField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('net_price', models.IntegerField(default=0)),
                ('gross_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Folyamatban'), ('completed', 'Teljesítve'), ('cancelled', 'Lemondva')], max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'Készpénz'), ('card', 'Utalás')], max_length=50)),
                ('delivery_mode', models.CharField(choices=[('personal', 'Személyes átvétel'), ('delivery', 'Szállítás')], max_length=50)),
                ('shipping_zip_code', models.CharField(max_length=10)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_street_name', models.CharField(max_length=100)),
                ('shipping_house_number', models.CharField(max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('conn_sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_order.salesorder')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('original_producer', models.CharField(max_length=100)),
                ('original_net_price', models.IntegerField(default=0)),
                ('original_vat', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('delivery_note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_note.deliverynote')),
                ('package_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagetype')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
