# Generated by Django 4.0.2 on 2022-02-27 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Megrendelve'), ('billed', 'Számlázva'), ('on_delivery_note', 'Szállítólevélen')], max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'Készpénz'), ('card', 'Utalás')], max_length=20)),
                ('document_number_key', models.PositiveIntegerField(blank=True, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('final', models.BooleanField(default=False)),
                ('net_price', models.IntegerField(default=0)),
                ('gross_price', models.ImageField(default=0, upload_to='')),
                ('deleted', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipping_address_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('package_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.packagetype')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('sales_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_order.salesorder')),
            ],
        ),
    ]
