# Generated by Django 4.0.2 on 2022-04-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0002_salesitembase'),
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_name',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_net_price',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_package_display',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_package_quantity',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_producer',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_vat',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='package_type_id',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='salesitembase_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_core.salesitembase'),
            preserve_default=False,
        ),
    ]
