# Generated by Django 4.0.2 on 2022-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='gross_price',
            field=models.IntegerField(default=0),
        ),
    ]
