# Generated by Django 4.0.2 on 2022-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0002_alter_salesorder_gross_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='recording_date',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
