# Generated by Django 4.0.2 on 2022-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0003_remove_salesorder_recording_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='final',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='original_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='original_net_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='original_producer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='original_vat',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Folyamatban'), ('partially_completed', 'Részben teljesített'), ('completed', 'Teljesített'), ('cancelled', 'Lemondva')], max_length=20),
        ),
    ]
