# Generated by Django 4.0.2 on 2022-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0004_remove_salesorder_final_salesorderitem_original_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Készpénz'), ('card', 'Utalás')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Folyamatban'), ('partially_completed', 'Részben teljesítve'), ('completed', 'Teljesített'), ('cancelled', 'Lemondva')], max_length=50),
        ),
    ]
