# Generated by Django 4.0.2 on 2022-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0005_alter_salesorder_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_address_id',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_house_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_street_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_zip_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
