# Generated by Django 4.0.2 on 2022-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0006_remove_salesorder_shipping_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='shipping_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='shipping_house_number',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='shipping_street_name',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='shipping_zip_code',
            new_name='zip_code',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_mode',
            field=models.CharField(choices=[('personal', 'Személyes átvétel'), ('delivery', 'Szállítás')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Folyamatban'), ('partially_completed', 'Részben teljesítve'), ('completed', 'Teljesítve'), ('cancelled', 'Lemondva')], max_length=50),
        ),
    ]
