# Generated by Django 4.0.2 on 2022-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0007_rename_shipping_city_salesorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='original_unit_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
