# Generated by Django 4.0.2 on 2022-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0008_salesorderitem_original_unit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='original_unit_quantity',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='original_package_display',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='original_package_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
