# Generated by Django 4.0.2 on 2022-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0010_alter_salesorderitem_sales_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
