# Generated by Django 4.0.2 on 2022-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0011_salesorder_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customer_last_name',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='original_customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
