# Generated by Django 4.0.2 on 2022-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceipt',
            name='finalization_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
