# Generated by Django 4.0.2 on 2022-03-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_receipt', '0004_remove_productreceiptitem_original_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreceiptitem',
            name='product_receipt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_receipt.productreceipt'),
        ),
    ]
