# Generated by Django 4.0.2 on 2022-02-19 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
