# Generated by Django 4.0.2 on 2022-02-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='topic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.faqtopic'),
            preserve_default=False,
        ),
    ]
