# Generated by Django 4.0.2 on 2022-02-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
